dist: focal
addons:
  apt:
    sources:
      - sourceline: 'ppa:chris-lea/redis-server'
    packages:
    - tesseract-ocr
    - libtesseract-dev
    - libleptonica-dev

language: python

services:
  - docker

before_install:
  - cat /etc/apt/sources.list
  - docker build -t badgerdoc .
  - docker images
